### ISSUE TITLE
Feature Request | st_desc_view command

### ISSUE THREAD

**Issue by gmonaie** [mtxr/SublimeText-SQLTools#187]
### Issue Type

Feature Request | st_desc_view

### Description

Show description of database views to match the command features already provided for st_desc_table and st_desc_function. We can then add these to the sublime key-map

**Comment by tkopets** [comment]
Generally, if DB CLI or RDBMS can describe the view with the same command as describing the table - SQLTools includes those views and lists those views as a table.
Which RDBMS are you using?

**Comment by gmonaie** [comment]
postgres 9.5 and sublime text on OS X

**Comment by tkopets** [comment]
SQLTools includes the views along with the tables when doing `ST: Table Description` if RDBMS/CLI suports this.
