### ISSUE TITLE
Can't view history

### ISSUE THREAD

**Issue by prabinsh** [mtxr/SublimeText-SQLTools#195]
> This issue template helps us understand your SQLTools issues better. 
>
> You don't need to stick to this template, but please try to guide us to reproduce the errors or understand your feature requests. 
> 
> Before submitting an issue, please consider these things first: 
> * Are you running the latest version? If not, try to upgrade.
> * Did you check the [Setup Guide](http://mtxr.github.io/SQLTools/)?
> * Did you check the logs in console (``Ctrl+` `` or select *View → Show Console*)?

### Issue Type

Bug/Error |

### Description

Getting following issue when checking history

Traceback (most recent call last):
  File "C:\Users\a\Documents\Sublime Text Build 3143 x64\sublime_plugin.py", line 797, in run_
    return self.run()
  File "C:\Users\a\Documents\Sublime Text Build 3143 x64\Data\Packages\SQLTools\SQLTools.py", line 612, in run
    if len(history.all()) == 0:
AttributeError: 'NoneType' object has no attribute 'all'

### Version

- *SQLTools Version*: 3143
- *OS*: Windows
- *RDBMS*: Oracle

> You can get this information by executing `ST: About` from Sublime `Command Palette`.

### Steps to Reproduce (For bugfixes)

1. Ctrl+e, Ctrl+h
2. [Second Step]
3. [and so on...]

**Expected behavior:** Show History

**Actual behavior:** Doesn't do anything

**Comment by tkopets** [comment]
Can you please review (or post here) the entire console output to see if there are any other SQLTools errors appear in sublime console before the error you posted above (e.g. any errors during plugin loading)?

**Comment by prabinsh** [comment]
Hello,
Console doesn't show anything else. The following commands aren't working so far.
View Queries history   CTRL+e, CTRL+h
Save queries   CTRL+e, CTRL+q
List and Run saved queries   CTRL+e, CTRL+l
Remove saved queries   CTRL+e, CTRL+r

**Comment by tkopets** [comment]
This issue should be fixed in the most recent release `v0.9.12`.
