### ISSUE TITLE
[DUDE] Code completation in *.php

### ISSUE THREAD

**Issue by marcoas** [mtxr/SublimeText-SQLTools#199]
Hi

In the documentation is this example configuration ...
```
{
  "auto_complete_triggers": [
    {"selector": "text.html", "characters": "<" },
    {"selector": "source.sql", "characters": "."}
  ]
}
```

But can I configure it to work in any project file (\*.\*) Or in the project's php files (*.php)?

**Comment by tkopets** [comment]
Autocompletion is shown only within certain code blocks configured by setting `selectors` in SQLTools settings (`ST: Settings`).
You can add additional selectors there as shown below (note the last two items in the list below):
```
// .......
"selectors": [
        "source.sql",
        "source.pgsql",
        "source.plpgsql.postgres",
        "source.plsql.oracle",
        "source.tsql",
        "source.php",
        "embedding.php",
    ],
// .......
```
However, please note that completions are not shown inside the strings (this is hardcoded and not configurable) - that was made to aviod showing completion when those are not needed, but in case of PHP this is almost always the case that you have your SQL inside a string. I will try to fix this in next SQLTools release.

**Comment by tkopets** [comment]
Thanks for this code snippet, I will make the appropriate adjustments and try to make it work with your sample.

**Comment by marcoas** [comment]
Could it also be possible to ask for the value of the variables included in the string?

In the following example, it would be that you ask for the value of **$date**

```
<?php
  ...
$sqlDatos = "SELECT  dps_ma1creqleg.d_req_leg,
                    dps_ma1caplica.d_aplicacion AS d_aplicacion,

               FROM dps_rg1creqleg 

              WHERE dps_rg1creqleg.fecha_prox_alerta = '$date'";
 ... 
```

**Comment by marcoas** [comment]
Thank You ! 
When will the update be available from SublimeText?
