### ISSUE TITLE
Project homepage 

### ISSUE THREAD

**Issue by slloyd88** [mtxr/SublimeText-SQLTools#216]
Your project homepage gives a 404 error. https://code.mteixeira.dev/SQLTools/

**Comment by slloyd88** [comment]
Your project homepage gives a 404 error.  https://code.mteixeira.dev/SQLTools/

**Comment by tkopets** [comment]
Here is a new one:
[https://code.mteixeira.dev/SublimeText-SQLTools/](https://code.mteixeira.dev/SublimeText-SQLTools/)

Thank you for reporting this - I will fix it soonish.
I can see the references to the old website address in the README file.
Is there any other place that points to the old site?
