### ISSUE TITLE
setup conn

### ISSUE THREAD

**Issue by slloyd88** [mtxr/SublimeText-SQLTools#217]
The readme needs to explain how to setup your connection after installatioin

**Comment by slloyd88** [comment]
Readme needs to explain how to setup your connection after you install

**Comment by tkopets** [comment]
There is a section about Connections on the website (see link below).
[https://code.mteixeira.dev/SublimeText-SQLTools/](https://code.mteixeira.dev/SublimeText-SQLTools/)

Readme most probably should point to the relevant section of the website.
If we duplicate this info in Readme and website it will require additional time to maintain both descriptions to keep them in sync.

**Comment by tkopets** [comment]
Have you managed to set up your connections?

**Comment by slloyd88** [comment]
Working on it now.  Hey, so if I have a php page and am coding a SQL query, can I highlight the SQL and run it?

**Comment by tkopets** [comment]
> Hey, so if I have a php page and am coding a SQL query, can I highlight the SQL and run it?

If your selection is a valid SQL query, then yes.
But if your SQL is built by string concatenation or contains some kind of parameters then most probably no.

> What if I have multiple databases? Can I have more than one Mysql databases?

Create multiple connections via `ST: Setup Connections` - one connection for each database.
You can switch between those connections via `ST: Select Connection`.

**Comment by slloyd88** [comment]
Sweet.  My Oracle connection failed because it uses a SID not a service.  I tried to specify the SID in the settings but it failed.

**Comment by tkopets** [comment]
Readme now has configuration section and links to the website for further details.
