### ISSUE TITLE
Add a means to see the last result when using the output panel. Something like "show_output_panel". It should have the latest result, just like how it will behave if you were showing the result on a view.

### ISSUE THREAD

**Issue by robertmarley** [mtxr/SublimeText-SQLTools#220]
### Issue Type
Feature Request 

### Description
Add a means to see the last result when using the output panel. Something like "show_output_panel". It should have the latest result, just like how it will behave if you were showing the result on a view.

### Version
- *SQLTools Version*: v0.9.9
- *OS*: Windows
- *RDBMS*: Oracle

**Comment by tkopets** [comment]
### Using mouse
You can see the list of all output panels in Sublime by clicking on the "panel" icon in the bottom lower-left corner.
After running the query left-click on that icon and choose `Output: SQLTools Result`

### Using keyboard
You can do it by combining existing built-in Sublime commands.

Go to `Preferences` -> `Key Bindings`

Add this custom key binding to your config (adjust the key sequence to your liking):
```
{ "keys": ["ctrl+e", "ctrl+p"], "command": "show_panel", "args": {"panel": "output.SQLTools Result"} },
```
Use `Ctr+e Ctrl+p` to show the last result (or whatever key-sequence you have put in config file above).

**Comment by robertmarley** [comment]
Thank you!

**Comment by robertmarley** [comment]
Should probably add this by default, and the doc on package control.
